# See the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: bun
    directory: /
    schedule:
      interval: daily
      timezone: Africa/Nairobi
    cooldown:
      default-days: 3
    groups:
      tailwindcss:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/vite"
      pg:
        patterns:
          - "pg"
          - "@types/pg"
      drizzle:
        patterns:
          - drizzle-orm
          - drizzle-kit
