---
useTabs: true
singleQuote: false
trailingComma: none
printWidth: 80
tailwindStylesheet: ./src/app.css
plugins:
  - prettier-plugin-svelte
  - prettier-plugin-tailwindcss # must come last
overrides:
  - files: "*.svelte"
    options:
      parser: svelte